apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-heart-api
  labels:
    app: heart-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: heart-api
  template:
    metadata:
      labels:
        app: heart-api
      annotations:
        prometheus.io/scrape: {{ .Values.metrics.scrape | quote }}
        prometheus.io/port: {{ .Values.metrics.port | quote }}
        prometheus.io/path: {{ .Values.metrics.path | quote }}
    spec:
      containers:
        - name: heart-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
