{
 "title": "Heart Disease API - Monitoring",
 "tags": [
  "mlops",
  "heart-disease"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate (req/s) by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_requests_total[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "p95 Request Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, endpoint) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Predictions by Class",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "predictions_total", "legendFormat": "{{predicted_label}}" }
   ]
  },
  {
   "title": "Total Requests by HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_status) (http_requests_total)",
     "legendFormat": "status {{http_status}}"
    }
   ]
  },
  {
   "title": "Total Predictions Served",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sum(predictions_total)" }
   ]
  }
 ]
}